SolutionName.Web/Models/User/ForgotPasswordViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace SolutionName.Web.Models.User;
public class ForgotPasswordViewModel
{
    [Required]
    public string Email { get; set; }
    
}

SolutionName.Web/Models/User/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace SolutionName.Web.Models.User;  
public class LoginViewModel
{       
    [Required]
    [EmailAddress]
    public string Email { get; set; }

    [Required]
    public string Password { get; set; }

}

SolutionName.Web/Models/User/PasswordViewModel.cs
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc;

namespace SolutionName.Web.Models.User;
public class PasswordViewModel
{
    public int Id { get; set; }

    [Required]
    [Remote(action: "VerifyPassword", controller: "User")]
    public string OldPassword { get; set; }
    
    [Required]
    public string Password { get; set; }

    [Compare("Password", ErrorMessage = "Confirm password doesn't match, Type again !")]
    public string PasswordConfirm  { get; set; }

}

SolutionName.Web/Models/User/ProfileViewModel.cs
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc;
using SolutionName.Data.Entities;

namespace SolutionName.Web.Models.User;
public class ProfileViewModel
{
    public int Id { get; set; }

    [Required]
    public string Name { get; set; }

    [Required]
    [EmailAddress]
    [Remote(action: "VerifyEmailAvailable", controller: "User", AdditionalFields = nameof(Id))]
    public string Email { get; set; }

    [Required]
    public Role Role { get; set; }

}

SolutionName.Web/Models/User/RegisterViewModel.cs
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;
using Microsoft.AspNetCore.Mvc;
using SolutionName.Data.Entities;

namespace SolutionName.Web.Models.User;

public class RegisterViewModel
{ 
    [Required]
    public string Name { get; set; }

    [Required]
    [EmailAddress]
    [Remote(action: "VerifyEmailAvailable", controller: "User")]
    public string Email { get; set; }

    [Required]
    public string Password { get; set; }

    [Compare("Password", ErrorMessage = "Confirm password doesn't match, Type again !")]
    public string PasswordConfirm  { get; set; }

    [Required]
    [JsonConverter(typeof(JsonStringEnumConverter))]
    public Role Role { get; set; }

}

SolutionName.Web/Models/User/ResetPasswordViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace SolutionName.Web.Models.User;
public class ResetPasswordViewModel
{
    [Required]
    public string Email { get; set; }
    
    [Required]
    public string Token { get; set; }

    [Required]
    public string Password { get; set; }

    [Compare("Password", ErrorMessage = "Confirm password doesn't match, Type again !")]
    public string PasswordConfirm  { get; set; }
    
}

SolutionName.Web/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;

using SolutionName.Data.Entities;
using SolutionName.Data.Services;
using Microsoft.AspNetCore.Authorization;
using SolutionName.Data.Security;
using SolutionName.Web.Models.User;

/**
 *  User Management Controller
 */
namespace SolutionName.Web.Controllers
{
    public class UserController : BaseController
    {
        private readonly IConfiguration _config;
        private readonly IMailService _mailer;
        private readonly IUserService _svc;

        public UserController(IUserService svc, IConfiguration config, IMailService mailer)
        {        
            _config = config;
            _mailer = mailer;
            _svc = svc;
        }

        // HTTP GET - Display Paged List of Users
        [Authorize]
        public ActionResult Index(int page=1, int size=20, string order="id", string direction="asc")
        {
            var paged = _svc.GetUsers(page,size,order,direction);      
            return View(paged);
        }

        // HTTP GET - Display Login page
        public IActionResult Login()
        {
            return View();
        }

        // HTTP POST - Login action
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login([Bind("Email,Password")] LoginViewModel m)
        {
            var user = _svc.Authenticate(m.Email, m.Password);
            // check if login was unsuccessful and add validation errors
            if (user == null)
            {
                ModelState.AddModelError("Email", "Invalid Login Credentials");
                ModelState.AddModelError("Password", "Invalid Login Credentials");
                return View(m);
            }

            // Login Successful, so sign user in using cookie authentication
            await SignInCookie(user);

            Alert("Successfully Logged in", AlertType.info);

            return Redirect("/");
        }

        // HTTP GET - Display Register page
        public IActionResult Register()
        {
            return View();
        }

        // HTTP POST - Register action
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Register([Bind("Name,Email,Password,PasswordConfirm,Role")] RegisterViewModel m)       
        {
            if (!ModelState.IsValid)
            {
                return View(m);
            }
            // add user via service
            var user = _svc.AddUser(m.Name, m.Email,m.Password, m.Role);
            
            // check if error adding user and display warning
            if (user == null) {
                Alert("There was a problem Registering. Please try again", AlertType.warning);
                return View(m);
            }

            Alert("Successfully Registered. Now login", AlertType.info);
            return RedirectToAction(nameof(Login));
        }

        // HTTP GET - Display Update profile page
        [Authorize]
        public IActionResult UpdateProfile()
        {
           // use BaseClass helper method to retrieve Id of signed in user 
            var user = _svc.GetUser(User.GetSignedInUserId());
            var profileViewModel = new ProfileViewModel { 
                Id = user.Id, 
                Name = user.Name, 
                Email = user.Email,                 
                Role = user.Role
            };
            return View(profileViewModel);
        }

        // HTTP POST - Update profile action
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateProfile([Bind("Id,Name,Email,Role")] ProfileViewModel m)       
        {
            var user = _svc.GetUser(m.Id);
            // check if form is invalid and redisplay
            if (!ModelState.IsValid || user == null)
            {
                return View(m);
            } 

            // update user details and call service
            user.Name = m.Name;
            user.Email = m.Email;
            user.Role = m.Role;        
            var updated = _svc.UpdateUser(user);

            // check if error updating service
            if (updated == null) {
                Alert("There was a problem Updating. Please try again", AlertType.warning);
                return View(m);
            }

            Alert("Successfully Updated Account Details", AlertType.info);
            
            // sign the user in with updated details)
            await SignInCookie(user);

            return RedirectToAction("Index","Home");
        }

        // HTTP GET - Allow admin to update a User
        [Authorize(Roles="admin")]
        public IActionResult Update(int id)
        {
           // retrieve user 
            var user = _svc.GetUser(id);
            var profileViewModel = new ProfileViewModel { 
                Id = user.Id, 
                Name = user.Name, 
                Email = user.Email,                 
                Role = user.Role
            };
            return View(profileViewModel);
        }

        // HTTP POST - Update User action
        [Authorize(Roles="admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update([Bind("Id,Name,Email,Role")] ProfileViewModel m)       
        {
            var user = _svc.GetUser(m.Id);
            // check if form is invalid and redisplay
            if (!ModelState.IsValid || user == null)
            {
                return View(m);
            } 

            // update user details and call service
            user.Name = m.Name;
            user.Email = m.Email;
            user.Role = m.Role;        
            var updated = _svc.UpdateUser(user);

            // check if error updating service
            if (updated == null) {
                Alert("There was a problem Updating. Please try again", AlertType.warning);
                return View(m);
            }

            Alert("Successfully Updated User Account Details", AlertType.info);                       

            return RedirectToAction("Index","User");
        }
        
        // HTTP GET - Display update password page
        [Authorize]
        public IActionResult UpdatePassword()
        {
            // use BaseClass helper method to retrieve Id of signed in user 
            var user = _svc.GetUser(User.GetSignedInUserId());
            var passwordViewModel = new PasswordViewModel { 
                Id = user.Id, 
                Password = user.Password, 
                PasswordConfirm = user.Password, 
            };
            return View(passwordViewModel);
        }

        // HTTP POST - Update Password action
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdatePassword([Bind("Id,OldPassword,Password,PasswordConfirm")] PasswordViewModel m)       
        {
            var user = _svc.GetUser(m.Id);
            if (!ModelState.IsValid || user == null)
            {
                return View(m);
            }  
            // update the password
            user.Password = m.Password; 
            // save changes      
            var updated = _svc.UpdateUser(user);
            if (updated == null) {
                Alert("There was a problem Updating the password. Please try again", AlertType.warning);
                return View(m);
            }

            Alert("Successfully Updated Password", AlertType.info);
            // sign the user in with updated details
            await SignInCookie(user);

            return RedirectToAction("Index","Home");
        }

        // HTTP POST - Logout action
        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction(nameof(Login));
        }


        // HTTP GET - Display Forgot password page
        public IActionResult ForgotPassword()
        {
            return View();            
        }

        // HTTP POST - Forgot password action
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult ForgotPassword([Bind("Email")] ForgotPasswordViewModel m)
        {           
            var token = _svc.ForgotPassword(m.Email);
            if (token == null)
            {
                // No such account. Alert only for testing
                Alert("No account found", AlertType.warning);
                return RedirectToAction(nameof(Login));
            }
            
            // build reset password url and email html message
            var url = $"{Request.Scheme}://{Request.Host}/User/ResetPassword?token={token}&email={m.Email}";
            var message = @$" 
                <h3>Password Reset</h3>
                <a href='{url}'>
                   {url}
                </a>
            ";
            
            // send email containing reset token
            if (!_mailer.SendMail( "Password Reset Request", message, m.Email ))
            {
                Alert("There was a problem sending a password reset email", AlertType.warning);
                return RedirectToAction(nameof(ForgotPassword));    
            }
            
            Alert("Password Reset Token sent to your registered email account", AlertType.info);
            return RedirectToAction(nameof(ResetPassword));
        }

        // HTTP GET - Display Reset password page
        public IActionResult ResetPassword()
        {
            return View();            
        }

        // HTTP POST - ResetPassword action
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult ResetPassword([Bind("Email,Password,Token")] ResetPasswordViewModel m)
        {
            // verify reset request
            var user = _svc.ResetPassword(m.Email, m.Token, m.Password);

SolutionName.Web/Views/Shared/Components/Paginator/PaginatorViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace SolutionName.Web.Views.Shared.Components;

[ViewComponent]
public class PaginatorViewComponent : ViewComponent
{
    
    public IViewComponentResult Invoke(string action, int rows, int pages, int current, int size=10)
    {       
        // extract existing query parameters except for page and size (these will be replaced with updated values)
        var existingParams = Request.Query
            .Where(e => e.Key.ToLower() != "page" && e.Key.ToLower() != "size")
            .Select(e =>  (e.Key.ToString(),e.Value.ToString())) 
            .ToList();
        
        // build paginator pages (page no and url)
        var pageLinks = new List<Page>();
        for(var p=1; p<=pages;  p++)
        {       
            pageLinks.Add( new Page(p, BuildUrl(action, p, size, existingParams)) ); 
        }

        var props = new PaginatorProps {           
            Pages = pageLinks, 
            CurrentPage = current, 
            TotalRows = rows, 
            PageSize = size,
         };
        return View("Default", props);
    }

    // build a url for action with existing parameters plus updated page and size parameters
    private string BuildUrl(string action, int page, int size, List<(string,string)> existingParameters)
    {
        var paramsDict = new RouteValueDictionary();
        existingParameters.ForEach( p => paramsDict.Add(p.Item1,p.Item2));
        paramsDict.Add("page", page);
        paramsDict.Add("size", size); 
        return Url.Action(action, paramsDict);
    }
}

public record Page(int PageNo, string Url);

public class PaginatorProps 
{
    private int Index => CurrentPage-1; // actual Pages index

    public int CurrentPage { get; set; } // 1..Pages.Count
    public List<Page> Pages { get; set; }
    public int TotalRows { get; set; }
    public int PageSize { get; set; }

    // read-only props
    public int TotalPages => Pages.Count;
    public Page NextPage => HasNextPage ? Pages[Index+1] : null;
    public Page PreviousPage => HasPreviousPage ? Pages[Index-1] : null;
    public Page FirstPage => Pages.FirstOrDefault();
    public Page LastPage => Pages.LastOrDefault();
 
    public bool HasPreviousPage => CurrentPage > 1;
    public bool HasNextPage => CurrentPage < TotalPages;
    public bool AtLastPage => !HasNextPage;
    public bool AtFirstPage => !HasPreviousPage;
}

SolutionName.Web/Views/Shared/Components/SortOrder/SortOrderViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace SolutionName.Web.Views.Shared.Components;

[ViewComponent]
public class SortOrderViewComponent : ViewComponent
{

    public IViewComponentResult Invoke(string field="Id", string orderby="Id", string direction = "asc")
    {      
        return View("Default", new SortOrderProps(field.ToLower(), orderby.ToLower(), direction.ToLower()) );
    }
}

public record SortOrderProps(string Field ="Id", string OrderBy="Id", string Direction="asc");

SolutionName.Web/Views/User/ErrorNotAuthenticated.cshtml
<div class="card shadow p-4 mt-5 mx-auto w-50">
  
    <div class="position-absolute top-0 start-50 translate-middle rounded-circle bg-dark p-2">
        <svg  class="text-white" width="28" height="28" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-lock-fill" viewBox="0 0 16 16">
            <path d="M8 1a2 2 0 0 1 2 2v4H6V3a2 2 0 0 1 2-2zm3 6V3a3 3 0 0 0-6 0v4a2 2 0 0 0-2 2v5a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V9a2 2 0 0 0-2-2z"/>
        </svg>
    </div>
    
    <div class="card-body">
        <h4 class="card-title">Not Authenticated</h4>
        <p class="card-text">You must be authenticated to access this feature.</p>
        <a asp-controller="User" asp-action="Login" class="btn btn-primary">Login</a>
    </div>
</div>

SolutionName.Web/Views/User/ErrorNotAuthorised.cshtml
<div class="card shadow p-4 mt-5 mx-auto w-50">
  
    <div class="position-absolute top-0 start-50 translate-middle rounded-circle bg-dark p-2">
        <svg class="text-white" width="28" height="28" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-shield-fill-x" viewBox="0 0 16 16">
          <path d="M8 0c-.69 0-1.843.265-2.928.56-1.11.3-2.229.655-2.887.87a1.54 1.54 0 0 0-1.044 1.262c-.596 4.477.787 7.795 2.465 9.99a11.777 11.777 0 0 0 2.517 2.453c.386.273.744.482 1.048.625.28.132.581.24.829.24s.548-.108.829-.24a7.159 7.159 0 0 0 1.048-.625 11.775 11.775 0 0 0 2.517-2.453c1.678-2.195 3.061-5.513 2.465-9.99a1.541 1.541 0 0 0-1.044-1.263 62.467 62.467 0 0 0-2.887-.87C9.843.266 8.69 0 8 0zM6.854 5.146 8 6.293l1.146-1.147a.5.5 0 1 1 .708.708L8.707 7l1.147 1.146a.5.5 0 0 1-.708.708L8 7.707 6.854 8.854a.5.5 0 1 1-.708-.708L7.293 7 6.146 5.854a.5.5 0 1 1 .708-.708z"/>
        </svg>
    </div>

    <div class="card-body">
        <h4 class="card-title">Not Authorised</h4>
        <p class="card-text">You do not have the necessary privilege to access this feature.</p>
        <a asp-controller="User" asp-action="Login" class="btn btn-primary">Login</a>
    </div>
</div>

SolutionName.Web/Views/User/ForgotPassword.cshtml
@model ForgotPasswordViewModel

<div class="card shadow p-4 mt-5 mx-auto w-50">
  
    <div class="position-absolute top-0 start-50 translate-middle rounded-circle bg-dark p-2">
        <svg class="text-white" xmlns="http://www.w3.org/2000/svg" width="28" height="28" fill="currentColor" class="bi bi-question" viewBox="0 0 16 16">
            <path d="M5.255 5.786a.237.237 0 0 0 .241.247h.825c.138 0 .248-.113.266-.25.09-.656.54-1.134 1.342-1.134.686 0 1.314.343 1.314 1.168 0 .635-.374.927-.965 1.371-.673.489-1.206 1.06-1.168 1.987l.003.217a.25.25 0 0 0 .25.246h.811a.25.25 0 0 0 .25-.25v-.105c0-.718.273-.927 1.01-1.486.609-.463 1.244-.977 1.244-2.056 0-1.511-1.276-2.241-2.673-2.241-1.267 0-2.655.59-2.75 2.286zm1.557 5.763c0 .533.425.927 1.01.927.609 0 1.028-.394 1.028-.927 0-.552-.42-.94-1.029-.94-.584 0-1.009.388-1.009.94z"/>
        </svg>

    </div>

    <h3 class="my-3 mx-auto">Password Reset Request</h3>
    
    <form asp-action="ForgotPassword" method="post">

        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

        <div class=" mt-3">
            <label asp-for="Email" class="form-label"><i class="bi-envelope-fill me-2"></i>Email Address</label>
            <input type="email" asp-for="Email" class="form-control" />
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>
        
        <div class=" mt-3">
            <input type="submit" value="Confirm" class="btn btn-primary" />
            <a class="btn btn-secondary" asp-controller="User" asp-action="Login">Cancel</a>
        </div>

    </form>
</div>

@section Scripts {
@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SolutionName.Web/Views/User/Index.cshtml
@model Paged<User>

<h3 class="mb-3">User List</h3>
  
<table class="table table-hover">
    <thead>
        <tr>
            <th>
                Id
                <a asp-action="Index" 
                    asp-route-order="id" 
                    asp-route-direction=@Model.Direction 
                    asp-route-page=@Model.CurrentPage 
                    asp-route-size=@Model.PageSize >
                        <vc:sort-order field="id" orderby=@Model.OrderBy direction=@Model.Direction />  
                </a>  

            </th>
            <th>
                Name
                <a asp-action="Index" 
                    asp-route-order="name" 
                    asp-route-direction=@Model.Direction 
                    asp-route-page=@Model.CurrentPage 
                    asp-route-size=@Model.PageSize >
                    <vc:sort-order field="name" orderby=@Model.OrderBy direction=@Model.Direction />  
                </a>  
            </th>
            <th>
                Email
                <a asp-action="Index" 
                    asp-route-order="email" 
                    asp-route-direction=@Model.Direction 
                    asp-route-page=@Model.CurrentPage 
                    asp-route-size=@Model.PageSize >
                    <vc:sort-order field="email" orderby=@Model.OrderBy direction=@Model.Direction />  
                </a>      
            </th>
            <th>Role</th>   
            <th>Action</th>           
        </tr>
    </thead>
    <tbody>
        @foreach(var u in Model.Data) {
            <tr>
                <td>@u.Id</td>
                <td>@u.Name</td>
                <td>@u.Email</td>
                <td>@u.Role</td>  
                <td>
                    <a asp-action="Update" asp-route-id="@u.Id">
                        <i class="bi bi-pencil-fill"></i>
                    </a>                    
                </td>                
            </tr>
        }        
    </tbody>
</table>

<vc:paginator action="Index" rows=@Model.TotalRows pages=@Model.TotalPages current=@Model.CurrentPage size=@Model.PageSize  />

SolutionName.Web/Views/User/Login.cshtml
@model LoginViewModel

<div class="card shadow p-4 mt-5 mx-auto w-75">
  
    <div class="position-absolute top-0 start-50 translate-middle rounded-circle bg-dark p-2">
        <svg class="text-white" width="28" height="28" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M12 15V17M6 21H18C19.1046 21 20 20.1046 20 19V13C20 11.8954 19.1046 11 18 11H6C4.89543 11 4 11.8954 4 13V19C4 20.1046 4.89543 21 6 21ZM16 11V7C16 4.79086 14.2091 3 12 3C9.79086 3 8 4.79086 8 7V11H16Z" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path>
        </svg>
    </div>
    
    <h3 class="my-3 mx-auto">Login</h3>
    
    <form asp-action="Login" method="post">

        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

        <div class="">
            <label asp-for="Email" class="form-label"><i class="bi-envelope-fill"></i> Email</label>
            <input asp-for="Email" class="form-control" />
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>

        <div class=" mt-3">
            <label asp-for="Password" class="form-label"><i class="bi-shield-lock-fill"></i> Password</label>
            <input type="password" asp-for="Password" class="form-control" />
            <span asp-validation-for="Password" class="text-danger"></span>
        </div>

        <div class=" mt-3">
            <input type="submit" value="Login" class="btn btn-primary" />
            @* <a class="btn btn-secondary" asp-controller="Home" asp-action="Index">Cancel</a> *@
            <a class="btn btn-link ms-3" asp-controller="User" asp-action="ForgotPassword">Forgot password?</a>
        </div>
            
    </form>
    
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

SolutionName.Web/Views/User/Register.cshtml
@model RegisterViewModel

<div class="card shadow p-4 mt-5 mx-auto w-75">
    <div class="position-absolute top-0 start-50 translate-middle rounded-circle bg-dark p-2">
        <svg class="text-white" xmlns="http://www.w3.org/2000/svg" width="28" height="28" fill="currentColor" class="bi bi-person-fill-add" viewBox="0 0 16 16">
            <path d="M12.5 16a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7Zm.5-5v1h1a.5.5 0 0 1 0 1h-1v1a.5.5 0 0 1-1 0v-1h-1a.5.5 0 0 1 0-1h1v-1a.5.5 0 0 1 1 0Zm-2-6a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z"/>
            <path d="M2 13c0 1 1 1 1 1h5.256A4.493 4.493 0 0 1 8 12.5a4.49 4.49 0 0 1 1.544-3.393C9.077 9.038 8.564 9 8 9c-5 0-6 3-6 4Z"/>
        </svg>
    </div>

    <h3 class="my-3 mx-auto">Register</h3>

    <form asp-action="Register" method="post">

        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

        <div class="mt-3">
            <label asp-for="Name" class="form-label"><i class="bi-person-fill"></i> Name</label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>

        <div class="mt-3">
            <label asp-for="Email" class="form-label"><i class="bi-envelope-fill"></i> Email</label>
            <input asp-for="Email" class="form-control" />
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>

        <div class="row">
            <div class="col mt-3">
                <label asp-for="Password" class="form-label"><i class="bi-shield-lock-fill"></i> Password</label>
                <input type="password" asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>

            <div class="col mt-3">
                <label asp-for="PasswordConfirm" class="form-label">Password Confirm</label>
                <input type="password" asp-for="PasswordConfirm" class="form-control" />
                <span asp-validation-for="PasswordConfirm" class="text-danger"></span>
            </div>
        </div>

        <div class="mt-3">
            <label asp-for="Role" class="form-label"><i class="bi-person-badge-fill"></i> Role</label>
            <select asp-for="Role" asp-items="Html.GetEnumSelectList<Role>()" class="form-control">
                <option>Select Role</option>
            </select>
            <span asp-validation-for="Role" class="text-danger"></span>
        </div>

         <div class="mt-3">
            <input type="submit" value="Register" class="btn btn-primary" />
            @* <a class="btn btn-secondary" asp-controller="User" asp-action="Login">Cancel</a> *@
            <a class="btn btn-link ms-3" asp-controller="User" asp-action="Login">Already have an account?</a>
        </div>

    </form>
</div>

@section Scripts {
@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SolutionName.Web/Views/User/Update.cshtml
@model ProfileViewModel

<div class="card shadow p-4 mt-5 mx-auto w-75">
  
    <div class="position-absolute top-0 start-50 translate-middle rounded-circle bg-dark p-2">
        <svg class="text-white" width="28" height="28" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-fill" viewBox="0 0 16 16">
          <path d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H3Zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6Z"/>
        </svg>
    </div>
    
    <h3 class="my-3 mx-auto">Update User Account</h3>

    <form asp-action="Update" method="post">

        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

        <input asp-for="Id" type="hidden" />

        <div class="">
            <label asp-for="Name" class="form-label"><i class="bi-person-fill"></i> Name</label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>

        <div class="mt-3">
            <label asp-for="Email" class="form-label"><i class="bi-envelope-fill"></i> Email</label>
            <input asp-for="Email" class="form-control" />
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>

        <div class="mt-3">
            <label asp-for="Role" class="form-label"><i class="bi-person-badge-fill"></i> Role</label>
            <select asp-for="Role" asp-items="Html.GetEnumSelectList<Role>()" class="form-control">
                <option>Select Role</option>
            </select>
            <span asp-validation-for="Role" class="text-danger"></span>
        </div>

        <div class="mt-3">
            <input type="submit" value="Save" class="btn btn-primary" />
            <a class="btn btn-secondary" asp-controller="User" asp-action="Index">Cancel</a>
        </div>

    </form>
</div>

@section Scripts {
@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}